name: Auto PR Creation and Merge

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make file change (dummy update)
        run: |
          echo "// change $(date -u)" >> dummy-file.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: dummy update"
          branch: auto/update-${{ github.run_id }}
          delete-branch: true
          title: "Automated PR: dummy update"
          body: |
            This PR was automatically created by a GitHub Actions workflow.
          labels: |
            automerge

  automerge:
    needs: auto-pr
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Auto Merge PRs with Label
        uses: ahmadnassri/action-auto-merge@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          label: automerge
          require-review: false
