name: Generate PRs with Empty Commits

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 * * * *"  # Every hour

  workflow_dispatch:  # Manual trigger support

jobs:
  generate_prs:
    runs-on: ubuntu-latest

    env:
      NUM_PRS: 10  # Number of pull requests to generate per run

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config --global user.email "RunarokHrafn@gmail.com"
          git config --global user.name "Runarok"

      - name: Loop to create PRs
        run: |
          for i in $(seq 1 $NUM_PRS); do
            BRANCH="auto-pr-$(date +%s)-$i"
            git checkout -b $BRANCH
            git commit --allow-empty -m "Empty commit for PR #$i"
            git push origin $BRANCH

            # Create pull request using GitHub CLI
            gh pr create \
              --base main \
              --head $BRANCH \
              --title "Auto PR #$i" \
              --body "This is an auto-generated pull request #$i"

            # Merge the pull request
            PR_URL=$(gh pr view $BRANCH --json url -q .url)
            gh pr merge "$PR_URL" --merge --delete-branch --admin

            # Delay slightly to avoid API rate limit
            sleep 5
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
